### PR TITLE
The credentialprovider is always used to check whether it contains the appropriate authConfig

### PR DESCRIPTION
**Pull request by theburn**
When pulling the sandbox image, the ensureSandboxImageExists method is used to retrieve the image. In this method, the credentialprovider (essentially looking up $HOME/.docker/config.json) is used to obtain the authConfig. I hope that a similar approach can be implemented in the default PullImage to avoid the need for passing auth information through command-line or environment variables.

### CODE REVIEW

**Comment by nwneisen** [comment]
Hello @theburn :wave: Thank you for the PR! Could you please create an issue that describes what happened and why you feel this change is necessary? Thank you!

**Comment by neersighted** [comment]
Adding a note here that I'm really not sure if this makes sense; I don't think we want to hardcode knowledge of the CLI auth system into cri-dockerd here, however tempting it is. I see that the code is generic and comes from K8s, but I really want to dig into how else it is used/what assumptions are made before accepting a merge of this.

**Comment by nwneisen** [comment]
I would agree that I don't feel like this is something that should be done by `cri-dockerd`. I see `cri-dockerd` as an intermediary to pass messages between k8s and dockerd. Credential handling seems like something that should be handled on the dockerd side of things. Even the existing auth code around this change seems like more than `cri-dockerd` should be doing.

**Comment by neersighted** [comment]
There's not really a way for dockerd to "do auth" today -- the token has always come from the API client, and then the daemon interacts with the registry on behalf of the API client.

I'm not quite sure what is right here, but something containerd-y (write a file in a config) instead of using the CLI `~/.docker/config.json` + using credential helpers (which can be GUI programs!) is my first instinct.

**Comment by theburn** [comment]
Thank you all for your replies and discussion.

Firstly, the main inspiration for this PR comes from this part of the code: https://github.com/Mirantis/cri-dockerd/blob/master/core/sandbox_helpers.go#L419

This part of the code reads the `auth` config and generates `credentials` for pulling sandbox images.
I thought since the related functionality is already implemented here, maybe it can also be reused globally.

Secondly, when using `crictl` with `cri-dockerd` as the endpoint to pull images, the `--creds` or `--auth` parameters need to be explicitly added, while when using `containerd` as the endpoint, there is no need to add them. I hope `cri-dockerd` can also achieve similar effects.

These are the main reasons why I proposed this PR.
-----
However, after reading your discussion, I think your thoughts may be right. I also agree with your opinion that the authentication information should be left to docker, keeping `cri-dockerd` simple and pure.

Indeed, the scenarios of using both `crictl` and `cri-dockerd` are very rare, and we should maintain a simple design

**Pull request closed without merging**
