### PR TITLE
Parameterize more Makefile variables, add a --buildinfo flag

### LINKED ISSUE #30: Need method of providing git commit information
When not using `git` to build, but a release tarball

From https://github.com/Mirantis/cri-dockerd/issues/19#issuecomment-1005520300

Optionally also support SOURCE_DATE_EPOCH.

https://reproducible-builds.org/

### PR DESCRIPTION
**Pull request by evol262**
Allow for REVISION|GIT_COMMIT, VERSION, and others to be set by
Makefile users who may have this project in a submodule or different
repo.

Closes #30

### CODE REVIEW

**Comment by afbjorklund** [comment]
Unfortunately this didn't work anyway, due to using "LDFLAGS".

That's a standard variable for C programs, so it was `LDFLAGS=""`.

It needs to be something like GOLDFLAGS or whatever, more internal.

Worked around it, by setting LDFLAGS locally only for cri-dockerd.

**Comment by evol262** [comment]
This is surprising, since it's been tested and released in multiple places, but not as part of a layered build, I suppose.

Renamed in #34

**Comment by afbjorklund** [comment]
The build system (buildroot) sets all the files when building, so that's why it failed for the actual ISO build.

`... CPPFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2  " CXXFLAGS="-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2  " LDFLAGS="" FCFLAGS=" -O2 " FFLAGS=" -O2 " ...`

(and so on and so forth)

Also had to set VERSION, or it would try to ask git. Which would either be missing, or in the wrong repo...

```console
$ git describe --abbrev=0 --tags | sed -e 's/v//'
2021.02.4
```

Truncating the REVISION is an adventure in itself, so in the end it was easier to just hardcode/duplicate it.

```Makefile
# As of 2022-02-03
CRI_DOCKERD_VER = 0.2.0
CRI_DOCKERD_REV = a4d1895
CRI_DOCKERD_VERSION = a4d1895a2659ea9974bd7528a706592ab8b74181
```

Hopefully it can go back to `v0.2.1` soon

**Comment by afbjorklund** [comment]
Also made sure to set GO_VERSION, but it doesn't seem like it affected anything ?

It was hardcoded to 1.16.8 in the Makefile, for some reason. But was using go1.17

**Pull request merged**
