### PR TITLE
Use cni by default on Linux, too

### LINKED ISSUE #104: With cri-dockerd 0.2.4, K3s with docker via cri-dockerd on Ubuntu 22.04 fails even if --network-plugin=cni is configured
Up until 0.2.3, I was able to run K3s with docker on Ubuntu 22.04 using
```
apt update
apt remove -y moby-engine moby-containerd moby-runc   # needed on GitHub Action environment to remove conflicts with docker.io
apt install -y docker.io jq
curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest | jq -r '.assets[].browser_download_url' | grep jammy_amd64.deb | tee /dev/stderr | xargs curl -LO
apt install -y ./cri-dockerd_*.deb
curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --container-runtime-endpoint=unix:///var/run/cri-dockerd.sock --kubelet-arg=cgroup-driver=systemd
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
( set +x ; while true ; do if kubectl get nodes | tee /dev/stderr | grep -q '\bReady\b' ; then break ; else sleep 5 ; fi ; done )
```

The K3s cluster quickly stabilizes into
```
NAME                  STATUS     ROLES                  AGE   VERSION
docker.example.test   NotReady   control-plane,master   1s    v1.24.3+k3s1
NAME                  STATUS     ROLES                  AGE   VERSION
docker.example.test   NotReady   control-plane,master   6s    v1.24.3+k3s1
NAME                  STATUS   ROLES                  AGE   VERSION
docker.example.test   Ready    control-plane,master   11s   v1.24.3+k3s1
```

It still works today when I replace the `curl` selecting the cri-dockerd release with the last-working 0.2.3 tag:
```
curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/tags/v0.2.3 | jq -r '.assets[].browser_download_url' | grep jammy_amd64.deb | tee /dev/stderr | xargs curl -LO
```

Alas, with https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.4/cri-dockerd_0.2.4.3-0.ubuntu-jammy_amd64.deb the K3s cluster never gets to the Ready state.

The https://github.com/Mirantis/cri-dockerd/issues/93 and https://github.com/Mirantis/cri-dockerd/pull/99 indicate that with 0.2.4, `--network-plugin=cni` is needed to revert back to the pre-0.2.4 behaviour. So I changed the steps to add that option:
```
[...]
curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest | jq -r '.assets[].browser_download_url' | grep jammy_amd64.deb | tee /dev/stderr | xargs curl -LO
apt install -y ./cri-dockerd_*.deb

# override ExecStart, add the --network-plugin=cni option
mkdir /etc/systemd/system/cri-docker.service.d
( echo '[Service]' ; echo 'ExecStart=' ; sed 's/ExecStart=.*/& --network-plugin=cni/;t;d' /lib/systemd/system/cri-docker.service ) | sudo tee /etc/systemd/system/cri-docker.service.d/network-plugin.conf
systemctl daemon-reload
systemctl restart cri-docker

curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --container-runtime-endpoint=unix:///var/run/cri-dockerd.sock --kubelet-arg=cgroup-driver=systemd
[...]
```

However, the K3s cluster never gets to the Ready state. The journal has a stream of
```
k3s[2975]: E0805 08:24:09.548625    2975 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
k3s[2975]: E0805 08:24:14.569182    2975 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
k3s[2975]: E0805 08:24:19.589066    2975 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
```
messages.

The cri-dockerd seems to be running with the expected option:
```
# systemctl status cri-docker --lines=0
● cri-docker.service - CRI Interface for Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/cri-docker.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/cri-docker.service.d
             └─network-plugin.conf
     Active: active (running) since Fri 2022-08-05 08:23:13 UTC; 5min ago
TriggeredBy: ● cri-docker.socket
       Docs: https://docs.mirantis.com
   Main PID: 2803 (cri-dockerd)
      Tasks: 9
     Memory: 13.5M
        CPU: 2.014s
     CGroup: /system.slice/cri-docker.service
             └─2803 /usr/bin/cri-dockerd --container-runtime-endpoint fd:// --network-plugin=cni
```
What else besides `--network-plugin=cni` needs to be changed for 0.2.4 to make it work as well as 0.2.3 did?

### PR DESCRIPTION
**Pull request by evol262**
Closes #104

### CODE REVIEW

**Comment by afbjorklund** [comment]
I think the user needed to install the cni plugins, either way ? (for both "kubenet", and for "cni")

`NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: could not locate kubenet required CNI plugins [bridge host-local loopback] at [\"/opt/cni/bin\" \"/opt/cni/bin\"]`

The main difference is that they would now also need to install _something_ in `/etc/cni/net.d` ?

----

The code changes on the minikube end would be the same, as long as it is not "no-op".

There was an unfortunate shortcut, that avoided updating the config for "known" config...

```go
	if networkPlugin == "" {
		// no-op plugin
		return nil
	}
```

It now needs to **always** update the cri-docker systemd unit file, with the users choice.

**Comment by afbjorklund** [comment]
@evol262 : I don't fully understand why changing to CNI involves updating to go1.19 ?

https://github.com/Mirantis/cri-dockerd/pull/103/commits/0470631d9761252b3dc9efb3670f05b1ec8f037c

Seems like a separate change, one that quite recently hit Kubernetes (while still in RC)...

**Comment by adelton** [comment]
I just filed https://github.com/Mirantis/cri-dockerd/issues/104 where I describe that with 0.2.4, even explicitly setting `cni` (on Ubuntu 22.04) does not work. It seems like something else is needed, or something additional.

If it is now necessary to specify some options that were not needed with 0.2.3, it would be great if the .service file had support for EnvironmentFile so that people wouldn't need to fiddle with the systemd unit files directly.

But more important -- could the documentation get updated to describe how to achieve the exact 0.2.3 setup? I don't really care which plugin is used, I primary setup the K3s cluster to run GitHub Actions CI tests, so whichever was used and worked should likely be documented, if it cannot be the default anymore.

**Comment by adelton** [comment]
> This would change your script to:
> ... sed 's/ExecStart=.*/& --network-plugin=no-op/;t;d' ...

Actually, I found out that plain
```
... sed 's/ExecStart=.*/& --network-plugin=/;t;d'  ...
```
with no value for the parameter seems to work as well on 0.2.4.

**Comment by afbjorklund** [comment]
> With 1.24 as the first upstream release where `dockershim` is _really_ gone from upstream, it's a sane starting point for compatibility as the last "prerelease" version (if `0.1` was the handeover from upstream, and `0.2` was the rewrite/refactor/cleanup for 1.24) to expect that `cri-dockerd` users are likely to be on `1.24`, and not have `kubenet` available out of the box (unless it was packaged here, which I'd be happy to avoid), and will install some CNI as a mandatory part of cluster bringup.

It would have made sense, if 1.24 had made both CRI and CNI mandatory - but in the end, they did not.
In fact, this change is now **not** going to make it for 1.25 either - but for 1.26 it seems to be reasonable...

So I am not going to change anything wrt minikube, it would still run without CNI - unless requested to.

We offer `--cni=bridge`, for users that don't really care or just want something simple that works locally.
For multi-node clusters, I would _still_ recommend [flannel](https://github.com/coreos/flannel) (with vxlan) - even if it is not part of the "[plugins](https://github.com/containernetworking/plugins)"

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cni/bridge.go

```go
// bridge is what minikube defaulted to when `--enable-default-cni=true`
```

In fact, even previous releases were broken when using containerd - for precisely this issue (i.e. no CNI)

---

It is OK if cri-dockerd recommends using CNI, but it would have to be separately configured in minikube.

> It doesn't quite crashloop

Right, I think the cluster will be up - it is the CoreDNS pod that will fail to appear. And it **is** [documented](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network)...

I will revisit this during autumn, maybe as a part of upgrading kubernetes-cni from the current 0.8.7 :spider_web:

**Comment by afbjorklund** [comment]
> will revisit this during autumn, maybe as a part of upgrading kubernetes-cni from the current 0.8.7

changed it so that minikube will use cni when it uses cri, i.e. when not using dockershim (< k8s 1.24)

**Pull request merged**
