### PR TITLE
Fix metrics performance issue #15

### PR DESCRIPTION
**Pull request by OleksiiKhanin**
Details see https://github.com/Mirantis/cri-dockerd/issues/15

### CODE REVIEW

**Comment by chancez** [comment]
I might be hitting this with rancher-desktop, causing metrics-server to sometimes timeout. It takes 12 seconds to get stats from kubelet: ```
time curl https://192.168.192.50:10250/stats/summary?only_cpu_and_memory=true -k -v -H "Authorization: Bearer ${TOKEN}"
```

**Comment by chancez** [comment]
I can confirm this fixes the issue I'm seeing.

**Comment by wpwoodjr** [comment]
> I might be hitting this with rancher-desktop, causing metrics-server to sometimes timeout. It takes 12 seconds to get stats from kubelet:
> 
> ```
> time curl https://192.168.192.50:10250/stats/summary?only_cpu_and_memory=true -k -v -H "Authorization: Bearer ${TOKEN}"
> ```

I'm seeing the same behavior.

**Comment by pioh** [comment]
There are two errors in this code
https://go.dev/play/p/EDXoixwXL2M

Fix:
https://github.com/OleksiiKhanin/cri-dockerd/pull/1/files

**Comment by pioh** [comment]
Also docker container stat PrivateWorkingSet returning 0 on linux
https://github.com/moby/moby/blob/master/api/types/stats.go#L81

Comment says that this is windows memory stat and may be this fix required:
https://github.com/pioh/cri-dockerd/commit/6e887d6a20309d4328cbecf33a5f430e744af808

**Comment by chancez** [comment]
Good catch: https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables

**Comment by travisghansen** [comment]
Doesn’t look to me like the bugs mentioned above were addressed in the merged code?

**Comment by jandubois** [comment]
> Doesn’t look to me like the bugs mentioned above were addressed in the merged code?

No, they were not. Maybe someone needs to open them as additional PRs.

There are also changes required to the Github Action code to make it still build and test correctly (needs bump to Golang 1.18, and changes to the test runner command).

**Comment by jandubois** [comment]
> I'm tracing down [this moby issue](https://github.com/moby/moby/pull/43567) in GH runners, then building debs/rpms/static binaries before cutting a release once it's confirmed that it's actually moby

Thank you very much for looking into this!

**Comment by jandubois** [comment]
> I'm just gonna set a calendar reminder to check the issues/PRs so I don't let it languish.

Thanks, very much appreciated. Otherwise I can also ping Brent again, now that I know that he works with you. 😄

**Comment by travisghansen** [comment]
I'm unclear why it was merged as is if there are known issues? The `CommonMistakes` link explains pretty clearly that as-is the results will be erratic no?

**Comment by travisghansen** [comment]
Ah! I missed it being included in the other PR, sorry for the confusion!

**Comment by gglnp** [comment]
Can --docker be re supported after k3s?

I originally wanted to install v1.24, but it doesn't support docker, so I had to install cri-docker. I don't know whether it's my problem or the cri-docker service problem. There is no problem with the installation, the service can't work, and the error message indicates that it needs to rely on.

I can only choose V1.23 without experiencing the latest version.

**Pull request merged**
