### PR TITLE
chore: rename systemd unit file

### LINKED ISSUE #27: Change the documentation to match the systemd unit files
~~Need the new "cri-dockerd" name, too. So that it matches the README~~

`systemctl enable --now cri-dockerd.socket`

Since:
* #24

---

Alternatively, the README could be updated to reflect the systemd units ?

That is: keep the "cri-docker" name, and make sure everyone uses that.

`systemctl enable --now cri-docker.socket`

### PR DESCRIPTION
**Pull request by tao12345666333**
fixes #27 

Although this is not mandatory, but this way we can make them all consistent.

### CODE REVIEW

**Comment by afbjorklund** [comment]
Why would it not be mandatory ?

**Review by afbjorklund — CHANGES_REQUESTED** [review]
This needs updating too:

`PartOf=cri-docker.service`

**Comment by tao12345666333** [comment]
It is a habit to keep the unit/service name consistent with its socket file, and there is no mandatory requirement. (Please let me know if I remember wrong)

**Comment by tao12345666333** [comment]
I will update. Thanks!

**Comment by afbjorklund** [comment]
The name of the systemd files is magic, so needs to match between .service and .socket.

It doesn't have to match the files on disk, even if that could be a good thing for sanity.

**Comment by evol262** [comment]
It really doesn't need to match between `.service` and `.socket` either. All that matters is that the `.socket` matches what is in the `Requires=` stanza for `.service`.

I'm not against this PR, but it's worth pointing out that this is not even remotely a standard. It's fine for personal preference. Off the top of my head, at least the following do not align between the name of `.socket` and the actual socket:

* virtlogd.socket
* libvirtd-ro.socket
* avahi-daemon.socket
* dbus.socket

I'm sure the list goes on and on. 

Similarly, `ssd.service` on RPM-based distros and `ssh.service` on DEB-based distros (which used to be openssh, but still) have differed for decades. `docker.service` itself actually starts `dockerd`. 

The only consistency and sanity in naming service/socket files is one that everyone can with. So what do we want to live with?

**Comment by afbjorklund** [comment]
I'm OK with going with "cri-dockerd" everywhere, just have to update all the packaging and the scripts to match.

I guess was easier for containerd (with naming), when they put the daemon into the project name already... :-)

**Comment by afbjorklund** [comment]
I have left the units as "cri-docker" for now, matching the 0.2.0 release of cri-docker (except the README)

The socket path has been updated to "cri-dockerd.sock", since it doesn't need to match the systemd units.

**Comment by afbjorklund** [comment]
@tao12345666333 : let's leave the systemd unit files as-is, and update the README instead ?

External documentation is now starting to use `cri-docker.socket` and `cri-dockerd.sock`already.

**Review by afbjorklund — CHANGES_REQUESTED** [review]
Leave the old names

**Comment by neolit123** [comment]
I am voting +1 for keeping all names the same, despite it is not a requirement.

From experience this can save everyone some minor future efforts. Examples:
- contributors sending PRs trying to rename these, at which point it can break a lot of users and the maintainers have to explain it
- someone wrapping cri-dockerd and realizing "hmm...the unit file does not have the d suffix for some reason"

**Comment by afbjorklund** [comment]
Once the packages appear (for cri-dockerd and cri-tools), hopefully the users don't have to do it manually.
The socket will start automatically (after the initial reboot), and `kubeadm` will find the new socket location.

So then it will "only" be a problem for developers, always something.

**Comment by tao12345666333** [comment]
@afbjorklund @neolit123 @evol262 I think we need to reach an agreement.

Once an agreement is reached here, then the subsequent documents, or user habits, will be gradually advanced in this way.

**Comment by afbjorklund** [comment]
I don't think we will change anything now, but it would be good to have the docs fixed before the beta ?

With Kubernetes v1.24.0-alpha.2 with "docker" container runtime and cri-dockerd v.0.2.0, you need to use:

`criSocket: /var/run/cri-dockerd.sock`

`systemctl enable --now cri-docker.socket`

**Comment by evol262** [comment]
I need to figure out why GH only gives me _some_ notifications about comments.

@afbjorklund do you mean that Kubernetes v1.24.0-alpha.2 has `cri-dockerd.socket`, not `cri-docker.socket`? If so, we'll change it here, since it's much faster than getting anything into upstream k8s

**Comment by neolit123** [comment]
> @neolit123
> I don't think we will change anything now, but it would be good to have the docs fixed before the beta ?

the problem i see with the name `cri-docker` is that it's not an existing project.
`cri-dockerd.socket` implies that it's a socket originating from the cri-dockerd project and avoids some of the minor issues mentioned [here](https://github.com/Mirantis/cri-dockerd/pull/31#issuecomment-1010760331).

> @afbjorklund do you mean that Kubernetes v1.24.0-alpha.2 has cri-dockerd.socket, not cri-docker.socket? If so, we'll change it here, since it's much faster than getting anything into upstream k8s

according to this tool, only minikube has adapted `cri-docker.socket` thus far:
https://grep.app/search?q=cri-docker.socket

the `unix:///var/run/cri-dockerd.sock` (Linux) and `npipe:////./pipe/cri-dockerd` (Windows) paths (+ some notes on what cri-dockerd is) are already merged in the kubernetes/website with preparation for the 1.24 release:
https://github.com/kubernetes/website/blob/dev-1.24/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md#installing-a-container-runtime-installing-runtime
these paths are also merged in the kubeadm 1.24 code.

but there are no mentions or uses of the `cri-docker.socket` systemd file in the k8s or kubeadm docs or code.
that is because, the plan for the k8s website at least is to link to cri-dockerd's repository and tell users that they need to follow the external guides to install the service. at that point `cri-docker.socket` would matter for users arriving here and following the setup - i.e. minikube is doing that already.

**Comment by evol262** [comment]
> the problem i see with the name `cri-docker` is that it's not an existing project.
> `cri-dockerd.socket` implies that it's a file originating from the cri-dockerd project and avoids some of the minor issues mentioned [here](https://github.com/Mirantis/cri-dockerd/pull/31#issuecomment-1010760331).

This is really not a great debate, since as my reply to you showed, the "implication" that it comes from whatever project is anything but a standard. There are >20 `.socket` files in RHEL and Ubuntu which don't consider that a standard or implication of any kind.

If anything, this follows the naming convention of `docker` itself, which ships `docker.service` and `docker.socket` for `dockerd`.

To put it this way: renaming is great if everyone agrees on it, but doing it because of some an assumed naming scheme which doesn't align with a large number of other projects (including Docker) is churn for churn's sake.

**Comment by neolit123** [comment]
> This is really not a great debate, since as my reply to you showed, the "implication" that it comes from whatever project is anything but a standard.

i think that was a [reply](https://github.com/Mirantis/cri-dockerd/pull/31#issuecomment-1006225187) to @afbjorklund 's comment.

> There are >20 .socket files in RHEL and Ubuntu which don't consider that a standard or implication of any kind.

Linux distributions have done a poor job around standardization, in general.

> If anything, this follows the naming convention of docker itself, which ships docker.service and docker.socket for dockerd.

that at least sounds like a consistency with dockerd, which is good.

**Comment by afbjorklund** [comment]
> do you mean that Kubernetes v1.24.0-alpha.2 has `cri-dockerd.socket`, not `cri-docker.socket`? If so, we'll change it here, since it's much faster than getting anything into upstream k8s

No, in Kubernetes v1.24.0-alpha.2 it is looking for `/var/run/cri-dockerd.sock` when it comes to the socket path.

The instructions are just referring to https://github.com/Mirantis/cri-dockerd which still says "cri-dockerd.socket"

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

The problem is that "cri-dockerd.socket" is **not** included in the cri-dockerd 0.2.0 release

> according to this tool, only minikube has adapted cri-docker.socket thus far:

We changed it twice, and can change it back. But would like to not have to version it based on Kubernetes version...

https://github.com/kubernetes/minikube/commit/f84ae2aaf7077d294eefa1bce5171f63572833d0 cri-dockerd.sock

https://github.com/kubernetes/minikube/commit/51b3f1c82b9503621ea9b94fbc37bd4b29b620f6 cri-docker.sock

https://github.com/kubernetes/minikube/commit/87249ab9ab62cbd64eca1f62315eec930b06cd78 cri-dockerd.sock

**Comment by afbjorklund** [comment]
Observation:
Most people seem to prefer to use cri-docker.service (rather than cri-docker.socket)

Probably because that is what containerd.service and cri-o.service are using now ?

`sudo systemctl restart containerd`

`sudo systemctl enable crio --now`

`# Run these commands as root`
`systemctl enable cri-dockerd.service`
`systemctl enable --now cri-dockerd.socket`

If the service (daemon) is already started at boot, then it doesn't need socket-activation.

But it could also mean that it is started even when it is not needed (i.e. no Kubernetes)

**Comment by evol262** [comment]
Ok. Socket activation notwithstanding, if kubernetes v1.24.0-alpha.2 is looking for `/var/run/cri-dockerd.sock`, let's run with that.

**Comment by evol262** [comment]
Note that, in any case, that's what's already in the systemd unit files, so no change needed there. This is simply about the names of the units themselves

**Pull request closed without merging**
